onlinejobportal/adminmodule/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
urlpatterns = [
  path('',projecthomepage,name="adminhomepage"),
  path('signup/',signup,name='signup'),
  path('signup1/', signup1, name='signup1'),
  path('login/',login,name='login'),
  path('login1/',login1,name='login1'),
  path('logout/',logout,name='logout'),

]

onlinejobportal/jobseekermodule/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
urlpatterns = [
  path('',projecthomepage,name="jobseekerhomepage"),
  path('viewjobs',viewjobs,name="viewjobs"),
  path('job_details_list', job_details_list, name="job_details_list"),
  path('submit_form/',submit_form,name='submit_form'),
  path('addjobseekerprofile/',addjobseekerprofile,name='addjobseekerprofile'),
  path('apply_to_job/<int:job_id>',apply_to_job,name='apply_to_job'),


]

onlinejobportal/onlinejobportal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('adminmodule.urls')),
    path('employer/',include('employermodule.urls')),
    path('jobseeker/',include('jobseekermodule.urls')),

]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinejobportal/employermodule/models.py
from django.db import models

# Create your models here.
class JobDetails(models.Model):
    work_title=models.CharField(max_length=255)
    salary_offered=models.CharField(max_length=255)
    JOB_TYPE =[
        ('fulltime','Full Time'),
        ('parttime','Part Time'),
        ('contract','Contract'),
    ]
    job_type=models.CharField(max_length=20,choices=JOB_TYPE)
    benefits=models.TextField()
    education=models.CharField(max_length=255)
    work_location=models.CharField(max_length=255)
    required_skills=models.TextField()

    def __str__(self):
        return self.work_title

onlinejobportal/jobseekermodule/models.py
from django.db import models

# Create your models here.
class Applicant(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    phone_number=models.CharField(max_length=10)
    address=models.TextField()
    tenth_marks=models.CharField(max_length=10)
    twelth_marks=models.CharField(max_length=10)
    cgpa=models.CharField(max_length=10)
    expected_salary=models.CharField(max_length=10)
    position=models.CharField(max_length=100)
    def __str__(self):
        return f"{self.first_name}{self.last_name}"

from employermodule.models import JobDetails
class JobApplication(models.Model):
    job_details=models.ForeignKey(JobDetails, on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    email=models.EmailField()
    resume=models.FileField(upload_to='resumes/')
    cover_letter=models.TextField()
    def __str__(self):
        return f"{self.name} {self.job_details}"

onlinejobportal/jobseekermodule/forms.py
from django import forms
from .models import *

class JobApplicationForm(forms.ModelForm):
    class Meta:
        model=JobApplication
        fields=['name','email','resume','cover_letter']
    def __init__(self,*args,**kwargs):
        super(JobApplicationForm,self).__init__(*args,**kwargs)

onlinejobportal/jobseekermodule/views.py
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect

from employermodule.models import JobDetails

from .models import *
from .forms import *


# Create your views here.

@login_required(login_url='login1')
def projecthomepage(request):
    return render(request,'jobseekerhomepage.html')
@login_required(login_url='login1')
def viewjobs(request):
    return render(request,'viewjobs.html')

@login_required(login_url='login1')
def job_details_list(request):
    job_details_list=JobDetails.objects.all()
    return render(request,'viewjobs.html',{'job_details_list':job_details_list})

@login_required(login_url='login1')
def addjobseekerprofile(request):
    return render(request,'jobseekerprofile.html')

@login_required(login_url='login1')
def submit_form(request):
    if request.method=='POST':
        first_name=request.POST['first_name']
        last_name=request.POST['last_name']
        phone_number=request.POST['phone_number']
        address=request.POST['address']
        tenth_marks=request.POST['10thMarks']
        twelth_marks=request.POST['12thMarks']
        cgpa=request.POST['cgpa']
        expected_salary=request.POST['expectedSalary']
        position=request.POST['position']

        applicant=Applicant(first_name=first_name,last_name=last_name,phone_number=phone_number,address=address,tenth_marks=tenth_marks,twelth_marks=twelth_marks,cgpa=cgpa, expected_salary=expected_salary,position=position)
        applicant.save()
        return render(request, 'jobseekerhomepage.html')
    return render(request, 'jobseekerprofile.html')


def apply_to_job(request,job_id):
    job_details=get_object_or_404(JobDetails,id=job_id)
    if request.method=='POST':
        form=JobApplicationForm(request.POST,request.FILES)
        if form.is_valid():
            job_application=form.save(commit=False)
            job_application.job_details=job_details
            job_application.save()

            subject='Job Application Received'
            message=('Thank you for applying to the Job. Your Application is received and will be sent to the next Process.\n\n'
                     f'Your Details\n'
                     f'Name: {job_application.name}\n\n\n\n'
                     
                     'Copyright A Sai Sankar - KLU. All rights reserved')
            from_email='saisankar3193@gmail.com'
            recipient_list=[job_application.email]
            send_mail(subject,message,from_email,recipient_list)
        return redirect('job_details_list')
    else:
        form=JobApplicationForm()

    return render(request,'apply_to_job.html',{'job_details':job_details,'form':form})

onlinejobportal/jobseekermodule/templates/apply_to_job.html
<!DOCTYPE html>
{% extends 'jobseekernavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}
<div class="container mt-5">
    <h2>Apply to Job</h2>

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ job_details.work_title }}</h5>
                    <p class="card-text">
                        <strong>Salary Offered:</strong> {{ job_details.salary_offered }}<br>
                        <strong>Job Type:</strong> {{ job_details.get_job_type_display }}<br>
                        <strong>Benefits:</strong> {{ job_details.benefits|linebreaks }}<br>
                        <strong>Education Requirements:</strong> {{ job_details.education }}<br>
                        <strong>Work Location:</strong> {{ job_details.work_location }}<br>
                        <strong>Required Skills:</strong> {{ job_details.required_skills|linebreaks }}
                    </p>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- Hidden field to store the job_id -->
                <input type="hidden" name="job_id" value="{{ job_details.id }}">

                <div class="form-group">
                    <label for="name">Your Name:</label>
                    <input type="text" class="form-control" name="name" required>
                </div>

                <div class="form-group">
                    <label for="email">Your Email:</label>
                    <input type="email" class="form-control" name="email" required>
                </div>

                <div class="form-group">
                    <label for="resume">Upload Resume:</label>
                    <input type="file" class="form-control-file" name="resume" accept=".pdf, .doc, .docx" required>
                </div>

                <div class="form-group">
                    <label for="cover_letter">Cover Letter:</label>
                    <textarea class="form-control" name="cover_letter" required></textarea>
                </div>

                <button type="submit" class="btn btn-success">Apply to this job</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

onlinejobportal/jobseekermodule/templates/jobseekerhomepage.html
<!DOCTYPE html>
{% extends 'jobseekernavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Job Seeker</title>
</head>
<body>
{% block body %}
<div id="carouselExampleIndicators" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://img.freepik.com/free-vector/man-search-hiring-job-online-from-laptop_1150-52728.jpg" class="d-block w-100" alt="emp">
    </div>
    <div class="carousel-item">
      <img src="https://www.shutterstock.com/image-photo/rear-view-brunette-woman-who-260nw-315858965.jpg" class="d-block w-100" alt="emp">
    </div>
    <div class="carousel-item">
      <img src="https://media.licdn.com/dms/image/C561BAQGnoaNjsBLsQg/company-background_10000/0/1590217283917/jobseeker_hub_cover?e=2147483647&v=beta&t=t6nbTjR1Y03y2g_YbID9SSXrMe5yRE9G4VsK91zzS18" class="d-block w-100" alt="emp">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
{% endblock%}
</body>
</html>

onlinejobportal/jobseekermodule/templates/jobseekernavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</head>
<body>

<nav class="navbar navbar-expand-lg " style="background-color: #00ff00">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'jobseekerhomepage'%}">Job Seeker Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'jobseekerhomepage'%}">Home</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'addjobseekerprofile'%}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'job_details_list' %}">View Jobs</a>
        </li>


      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <span class="navbar-text">

    <div>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      <!-- <li class="nav-item"> <a class="nav-link active" aria-current="page" href="{% url 'employerhomepage' %}">Employer</a></li>
        <li class="nav-item"> <a class="nav-link active" aria-current="page" href="{% url 'adminhomepage' %}">Admin</a></li>
      -->
           <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
      </ul>
    </div>

      </span>
    </div>
  </div>
</nav>
{% block body%}
{% endblock%}

<footer id ="sticky-footer" class="flex-shrink-0 py-2">
    <div class ="container text-center">
        <small>Copyright A Sai Sankar - KLU. All rights reserved</small>
    </div>
</footer>
<style>
    #sticky-footer {
    position:fixed;
    bottom:0;
    left:0;
    right:0;
    background-color: #17a2b8;
    color:white;
    padding: 10px;
    font-weight:bold;
    }
</style>
</body>
</html>

onlinejobportal/jobseekermodule/templates/jobseekerprofile.html
<!DOCTYPE html>
{% extends 'jobseekernavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}
<div>
    <h1>
        Job Seeker  Page
    </h1>
    <div>
        <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <title>Job Application Form</title>
</head>
<body>

<div class="container mt-5">
    <h2>Job Application Form</h2>
    <form method="post" action="{% url 'submit_form' %}">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="firstName">First Name</label>
                <input type="text" class="form-control" name ='first_name' id="first_name" placeholder="Enter your first name">
            </div>
            <div class="form-group col-md-6">
                <label for="lastName">Last Name</label>
                <input type="text" class="form-control" name ='last_name' id="last_name" placeholder="Enter your last name">
            </div>
        </div>

        <div class="form-group">
            <label for="phoneNumber">Phone Number</label>
            <input type="tel" class="form-control" name ='phone_number'  id="phoneNumber" placeholder="Enter your phone number">
        </div>

        <div class="form-group">
            <label for="address">Address</label>
            <input type="text" class="form-control" name ='address'  id="address" placeholder="Enter your address">
        </div>

        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="10thMarks">10th Marks</label>
                <input type="text" class="form-control" name ='10thMarks'  id="10thMarks" placeholder="Enter your 10th marks">
            </div>
            <div class="form-group col-md-4">
                <label for="12thMarks">12th Marks</label>
                <input type="text" class="form-control" name ='12thMarks'  id="12thMarks" placeholder="Enter your 12th marks">
            </div>
            <div class="form-group col-md-4">
                <label for="cgpa">CGPA</label>
                <input type="text" class="form-control" name ='cgpa' id="cgpa" placeholder="Enter your CGPA">
            </div>
        </div>

        <div class="form-group">
            <label for="expectedSalary">Expected Salary</label>
            <input type="text" class="form-control" name ='expectedSalary'  id="expectedSalary" placeholder="Enter your expected salary">
        </div>

        <div class="form-group">
            <label for="position">Position</label>
            <input type="text" class="form-control" name ='position'  id="position" placeholder="Enter the position you are applying for">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
        <br><br><br><br><br>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

</body>
</html>

    </div>
</div>
{% endblock %}
</body>
</html>

onlinejobportal/jobseekermodule/templates/viewjobs.html
<!DOCTYPE html>
{% extends 'jobseekernavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Job Seeker</title>
</head>
{% block body %}
<div class="container mt-5">
    <h2>Job Details List</h2>
    <div class="row">
        {% for job_details in job_details_list %}
        <div class="col-md-4 mb-4">
<div class="card" style="width: 18rem;">
   <div class="card-body">
    <h5 class="card-title">{{job_details.work_title}}</h5>
       <p class="card-text">Salary Offered: {{job_details.salary_offered}} </p>
       <p class="card-text">Job Type: {{job_details.job_type}} </p>
       <p class="card-text">Benefits: {{job_details.benefits}} </p>
       <p class="card-text">Education: {{job_details.education}} </p>
       <p class="card-text">Work Location: {{job_details.work_location}} </p>
       <p class="card-text">Required Skills: {{job_details.required_skills}} </p>

       <a href="{% url 'apply_to_job' job_details.id %}" class="btn btn-success">Apply to this Job</a>
   </div>
</div>
    </div>
         {% endfor %}
    </div>
</div>
{% endblock%}
</body>
</html>